spring:
  application:
    name: cxin-template
  profiles:
    active: local
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  # todo init
  datasource:
    url: jdbc:mysql://localhost:3306/table_name?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: password@WSX
      database: 0
server:
  port: 8567
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi 配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cxin.cxintemplate.controller
# knife4j 接口文档配置
knife4j:
  enable: true
  setting:
    language: zh_cn




